@host = http://127.0.0.1:8000

### Tillar ro'yxati
GET {{host}}/languages

### So'z qidirish (matn boshlanishi bo'yicha, ixtiyoriy til filtri)
GET {{host}}/words?q=about&language=en

### So'zni id orqali batafsil ko'rish (ta'rif, misol, tarjimalar bilan)
GET {{host}}/words/1

### uz tarjima yozuvini ko'rish (masalan "about"ning tarjimasi)
GET {{host}}/words/5190

### Sahifalash (limit/offset)
GET {{host}}/words?limit=5&offset=10

### Faqat uz so'zlar orasidan qidirish
GET {{host}}/words?q=hayd&language=uz

### Kurslar ro'yxati (Beginner, Essential)
GET {{host}}/courses

### Kursning boblari (chapters)
GET {{host}}/courses/1/chapters

### Bobning unitlari
GET {{host}}/chapters/1/units

### Unit ichidagi so'zlar (dars mazmuni)
GET {{host}}/units/1/words

### Hikoyalar ro'yxati
GET {{host}}/stories?limit=5

### Bitta hikoya
GET {{host}}/stories/1

### Mavjud bo'lmagan so'z (404 kutiladi)
GET {{host}}/words/999999
