"""initial schema

Revision ID: 357977ad7907
Revises: 
Create Date: 2026-09-21 23:44:53.203569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357977ad7907'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language')
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('from_language', sa.Integer(), nullable=False),
    sa.Column('to_language', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_language'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['to_language'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['language'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_story_id', sa.Integer(), nullable=False),
    sa.Column('to_story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['to_story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('used_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_type_id', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['word_type_id'], ['word_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_type_id', sa.Integer(), nullable=False),
    sa.Column('sample', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['word_type_id'], ['word_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabularies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_language', sa.Integer(), nullable=False),
    sa.Column('to_language', sa.Integer(), nullable=False),
    sa.Column('from_word_type', sa.Integer(), nullable=False),
    sa.Column('to_word_type', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.Column('replaced_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_language'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['from_word_type'], ['word_types.id'], ),
    sa.ForeignKeyConstraint(['replaced_by'], ['vocabularies.id'], ),
    sa.ForeignKeyConstraint(['to_language'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['to_word_type'], ['word_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_type_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['word_type_id'], ['word_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_sample_id', sa.Integer(), nullable=False),
    sa.Column('to_sample_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['to_sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('word_type_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['word_type_id'], ['word_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_words')
    op.drop_table('unit_pictures')
    op.drop_table('sample_translations')
    op.drop_table('word_pictures')
    op.drop_table('vocabularies')
    op.drop_table('units')
    op.drop_table('samples')
    op.drop_table('definitions')
    op.drop_table('chapter_pictures')
    op.drop_table('word_types')
    op.drop_table('used_words')
    op.drop_table('story_translations')
    op.drop_table('story_pictures')
    op.drop_table('course_pictures')
    op.drop_table('chapters')
    op.drop_table('words')
    op.drop_table('stories')
    op.drop_table('courses')
    op.drop_table('types')
    op.drop_table('languages')
    # ### end Alembic commands ###
